/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AllFeaturesRouteImport } from './routes/AllFeatures'
import { Route as IndexRouteImport } from './routes/index'

const VariableRowHeightLazyRouteImport = createFileRoute('/VariableRowHeight')()
const TreeViewLazyRouteImport = createFileRoute('/TreeView')()
const ScrollToCellLazyRouteImport = createFileRoute('/ScrollToCell')()
const RowsReorderingLazyRouteImport = createFileRoute('/RowsReordering')()
const RowGroupingLazyRouteImport = createFileRoute('/RowGrouping')()
const ResizableGridLazyRouteImport = createFileRoute('/ResizableGrid')()
const RangeSelectionLazyRouteImport = createFileRoute('/RangeSelection')()
const NoRowsLazyRouteImport = createFileRoute('/NoRows')()
const MillionCellsLazyRouteImport = createFileRoute('/MillionCells')()
const MasterDetailLazyRouteImport = createFileRoute('/MasterDetail')()
const InfiniteScrollingLazyRouteImport = createFileRoute('/InfiniteScrolling')()
const HeaderFiltersLazyRouteImport = createFileRoute('/HeaderFilters')()
const CustomizableRenderersLazyRouteImport = createFileRoute(
  '/CustomizableRenderers',
)()
const ContextMenuLazyRouteImport = createFileRoute('/ContextMenu')()
const CommonFeaturesLazyRouteImport = createFileRoute('/CommonFeatures')()
const ColumnsReorderingLazyRouteImport = createFileRoute('/ColumnsReordering')()
const ColumnSpanningLazyRouteImport = createFileRoute('/ColumnSpanning')()
const ColumnGroupingLazyRouteImport = createFileRoute('/ColumnGrouping')()
const CellNavigationLazyRouteImport = createFileRoute('/CellNavigation')()
const AnimationLazyRouteImport = createFileRoute('/Animation')()

const VariableRowHeightLazyRoute = VariableRowHeightLazyRouteImport.update({
  id: '/VariableRowHeight',
  path: '/VariableRowHeight',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/VariableRowHeight.lazy').then((d) => d.Route),
)
const TreeViewLazyRoute = TreeViewLazyRouteImport.update({
  id: '/TreeView',
  path: '/TreeView',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/TreeView.lazy').then((d) => d.Route))
const ScrollToCellLazyRoute = ScrollToCellLazyRouteImport.update({
  id: '/ScrollToCell',
  path: '/ScrollToCell',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/ScrollToCell.lazy').then((d) => d.Route))
const RowsReorderingLazyRoute = RowsReorderingLazyRouteImport.update({
  id: '/RowsReordering',
  path: '/RowsReordering',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/RowsReordering.lazy').then((d) => d.Route),
)
const RowGroupingLazyRoute = RowGroupingLazyRouteImport.update({
  id: '/RowGrouping',
  path: '/RowGrouping',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/RowGrouping.lazy').then((d) => d.Route))
const ResizableGridLazyRoute = ResizableGridLazyRouteImport.update({
  id: '/ResizableGrid',
  path: '/ResizableGrid',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/ResizableGrid.lazy').then((d) => d.Route))
const RangeSelectionLazyRoute = RangeSelectionLazyRouteImport.update({
  id: '/RangeSelection',
  path: '/RangeSelection',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/RangeSelection.lazy').then((d) => d.Route),
)
const NoRowsLazyRoute = NoRowsLazyRouteImport.update({
  id: '/NoRows',
  path: '/NoRows',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/NoRows.lazy').then((d) => d.Route))
const MillionCellsLazyRoute = MillionCellsLazyRouteImport.update({
  id: '/MillionCells',
  path: '/MillionCells',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/MillionCells.lazy').then((d) => d.Route))
const MasterDetailLazyRoute = MasterDetailLazyRouteImport.update({
  id: '/MasterDetail',
  path: '/MasterDetail',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/MasterDetail.lazy').then((d) => d.Route))
const InfiniteScrollingLazyRoute = InfiniteScrollingLazyRouteImport.update({
  id: '/InfiniteScrolling',
  path: '/InfiniteScrolling',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/InfiniteScrolling.lazy').then((d) => d.Route),
)
const HeaderFiltersLazyRoute = HeaderFiltersLazyRouteImport.update({
  id: '/HeaderFilters',
  path: '/HeaderFilters',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/HeaderFilters.lazy').then((d) => d.Route))
const CustomizableRenderersLazyRoute =
  CustomizableRenderersLazyRouteImport.update({
    id: '/CustomizableRenderers',
    path: '/CustomizableRenderers',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/CustomizableRenderers.lazy').then((d) => d.Route),
  )
const ContextMenuLazyRoute = ContextMenuLazyRouteImport.update({
  id: '/ContextMenu',
  path: '/ContextMenu',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/ContextMenu.lazy').then((d) => d.Route))
const CommonFeaturesLazyRoute = CommonFeaturesLazyRouteImport.update({
  id: '/CommonFeatures',
  path: '/CommonFeatures',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/CommonFeatures.lazy').then((d) => d.Route),
)
const ColumnsReorderingLazyRoute = ColumnsReorderingLazyRouteImport.update({
  id: '/ColumnsReordering',
  path: '/ColumnsReordering',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/ColumnsReordering.lazy').then((d) => d.Route),
)
const ColumnSpanningLazyRoute = ColumnSpanningLazyRouteImport.update({
  id: '/ColumnSpanning',
  path: '/ColumnSpanning',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/ColumnSpanning.lazy').then((d) => d.Route),
)
const ColumnGroupingLazyRoute = ColumnGroupingLazyRouteImport.update({
  id: '/ColumnGrouping',
  path: '/ColumnGrouping',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/ColumnGrouping.lazy').then((d) => d.Route),
)
const CellNavigationLazyRoute = CellNavigationLazyRouteImport.update({
  id: '/CellNavigation',
  path: '/CellNavigation',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/CellNavigation.lazy').then((d) => d.Route),
)
const AnimationLazyRoute = AnimationLazyRouteImport.update({
  id: '/Animation',
  path: '/Animation',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/Animation.lazy').then((d) => d.Route))
const AllFeaturesRoute = AllFeaturesRouteImport.update({
  id: '/AllFeatures',
  path: '/AllFeatures',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/AllFeatures.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/AllFeatures': typeof AllFeaturesRoute
  '/Animation': typeof AnimationLazyRoute
  '/CellNavigation': typeof CellNavigationLazyRoute
  '/ColumnGrouping': typeof ColumnGroupingLazyRoute
  '/ColumnSpanning': typeof ColumnSpanningLazyRoute
  '/ColumnsReordering': typeof ColumnsReorderingLazyRoute
  '/CommonFeatures': typeof CommonFeaturesLazyRoute
  '/ContextMenu': typeof ContextMenuLazyRoute
  '/CustomizableRenderers': typeof CustomizableRenderersLazyRoute
  '/HeaderFilters': typeof HeaderFiltersLazyRoute
  '/InfiniteScrolling': typeof InfiniteScrollingLazyRoute
  '/MasterDetail': typeof MasterDetailLazyRoute
  '/MillionCells': typeof MillionCellsLazyRoute
  '/NoRows': typeof NoRowsLazyRoute
  '/RangeSelection': typeof RangeSelectionLazyRoute
  '/ResizableGrid': typeof ResizableGridLazyRoute
  '/RowGrouping': typeof RowGroupingLazyRoute
  '/RowsReordering': typeof RowsReorderingLazyRoute
  '/ScrollToCell': typeof ScrollToCellLazyRoute
  '/TreeView': typeof TreeViewLazyRoute
  '/VariableRowHeight': typeof VariableRowHeightLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/AllFeatures': typeof AllFeaturesRoute
  '/Animation': typeof AnimationLazyRoute
  '/CellNavigation': typeof CellNavigationLazyRoute
  '/ColumnGrouping': typeof ColumnGroupingLazyRoute
  '/ColumnSpanning': typeof ColumnSpanningLazyRoute
  '/ColumnsReordering': typeof ColumnsReorderingLazyRoute
  '/CommonFeatures': typeof CommonFeaturesLazyRoute
  '/ContextMenu': typeof ContextMenuLazyRoute
  '/CustomizableRenderers': typeof CustomizableRenderersLazyRoute
  '/HeaderFilters': typeof HeaderFiltersLazyRoute
  '/InfiniteScrolling': typeof InfiniteScrollingLazyRoute
  '/MasterDetail': typeof MasterDetailLazyRoute
  '/MillionCells': typeof MillionCellsLazyRoute
  '/NoRows': typeof NoRowsLazyRoute
  '/RangeSelection': typeof RangeSelectionLazyRoute
  '/ResizableGrid': typeof ResizableGridLazyRoute
  '/RowGrouping': typeof RowGroupingLazyRoute
  '/RowsReordering': typeof RowsReorderingLazyRoute
  '/ScrollToCell': typeof ScrollToCellLazyRoute
  '/TreeView': typeof TreeViewLazyRoute
  '/VariableRowHeight': typeof VariableRowHeightLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/AllFeatures': typeof AllFeaturesRoute
  '/Animation': typeof AnimationLazyRoute
  '/CellNavigation': typeof CellNavigationLazyRoute
  '/ColumnGrouping': typeof ColumnGroupingLazyRoute
  '/ColumnSpanning': typeof ColumnSpanningLazyRoute
  '/ColumnsReordering': typeof ColumnsReorderingLazyRoute
  '/CommonFeatures': typeof CommonFeaturesLazyRoute
  '/ContextMenu': typeof ContextMenuLazyRoute
  '/CustomizableRenderers': typeof CustomizableRenderersLazyRoute
  '/HeaderFilters': typeof HeaderFiltersLazyRoute
  '/InfiniteScrolling': typeof InfiniteScrollingLazyRoute
  '/MasterDetail': typeof MasterDetailLazyRoute
  '/MillionCells': typeof MillionCellsLazyRoute
  '/NoRows': typeof NoRowsLazyRoute
  '/RangeSelection': typeof RangeSelectionLazyRoute
  '/ResizableGrid': typeof ResizableGridLazyRoute
  '/RowGrouping': typeof RowGroupingLazyRoute
  '/RowsReordering': typeof RowsReorderingLazyRoute
  '/ScrollToCell': typeof ScrollToCellLazyRoute
  '/TreeView': typeof TreeViewLazyRoute
  '/VariableRowHeight': typeof VariableRowHeightLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/AllFeatures'
    | '/Animation'
    | '/CellNavigation'
    | '/ColumnGrouping'
    | '/ColumnSpanning'
    | '/ColumnsReordering'
    | '/CommonFeatures'
    | '/ContextMenu'
    | '/CustomizableRenderers'
    | '/HeaderFilters'
    | '/InfiniteScrolling'
    | '/MasterDetail'
    | '/MillionCells'
    | '/NoRows'
    | '/RangeSelection'
    | '/ResizableGrid'
    | '/RowGrouping'
    | '/RowsReordering'
    | '/ScrollToCell'
    | '/TreeView'
    | '/VariableRowHeight'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/AllFeatures'
    | '/Animation'
    | '/CellNavigation'
    | '/ColumnGrouping'
    | '/ColumnSpanning'
    | '/ColumnsReordering'
    | '/CommonFeatures'
    | '/ContextMenu'
    | '/CustomizableRenderers'
    | '/HeaderFilters'
    | '/InfiniteScrolling'
    | '/MasterDetail'
    | '/MillionCells'
    | '/NoRows'
    | '/RangeSelection'
    | '/ResizableGrid'
    | '/RowGrouping'
    | '/RowsReordering'
    | '/ScrollToCell'
    | '/TreeView'
    | '/VariableRowHeight'
  id:
    | '__root__'
    | '/'
    | '/AllFeatures'
    | '/Animation'
    | '/CellNavigation'
    | '/ColumnGrouping'
    | '/ColumnSpanning'
    | '/ColumnsReordering'
    | '/CommonFeatures'
    | '/ContextMenu'
    | '/CustomizableRenderers'
    | '/HeaderFilters'
    | '/InfiniteScrolling'
    | '/MasterDetail'
    | '/MillionCells'
    | '/NoRows'
    | '/RangeSelection'
    | '/ResizableGrid'
    | '/RowGrouping'
    | '/RowsReordering'
    | '/ScrollToCell'
    | '/TreeView'
    | '/VariableRowHeight'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllFeaturesRoute: typeof AllFeaturesRoute
  AnimationLazyRoute: typeof AnimationLazyRoute
  CellNavigationLazyRoute: typeof CellNavigationLazyRoute
  ColumnGroupingLazyRoute: typeof ColumnGroupingLazyRoute
  ColumnSpanningLazyRoute: typeof ColumnSpanningLazyRoute
  ColumnsReorderingLazyRoute: typeof ColumnsReorderingLazyRoute
  CommonFeaturesLazyRoute: typeof CommonFeaturesLazyRoute
  ContextMenuLazyRoute: typeof ContextMenuLazyRoute
  CustomizableRenderersLazyRoute: typeof CustomizableRenderersLazyRoute
  HeaderFiltersLazyRoute: typeof HeaderFiltersLazyRoute
  InfiniteScrollingLazyRoute: typeof InfiniteScrollingLazyRoute
  MasterDetailLazyRoute: typeof MasterDetailLazyRoute
  MillionCellsLazyRoute: typeof MillionCellsLazyRoute
  NoRowsLazyRoute: typeof NoRowsLazyRoute
  RangeSelectionLazyRoute: typeof RangeSelectionLazyRoute
  ResizableGridLazyRoute: typeof ResizableGridLazyRoute
  RowGroupingLazyRoute: typeof RowGroupingLazyRoute
  RowsReorderingLazyRoute: typeof RowsReorderingLazyRoute
  ScrollToCellLazyRoute: typeof ScrollToCellLazyRoute
  TreeViewLazyRoute: typeof TreeViewLazyRoute
  VariableRowHeightLazyRoute: typeof VariableRowHeightLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/VariableRowHeight': {
      id: '/VariableRowHeight'
      path: '/VariableRowHeight'
      fullPath: '/VariableRowHeight'
      preLoaderRoute: typeof VariableRowHeightLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/TreeView': {
      id: '/TreeView'
      path: '/TreeView'
      fullPath: '/TreeView'
      preLoaderRoute: typeof TreeViewLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ScrollToCell': {
      id: '/ScrollToCell'
      path: '/ScrollToCell'
      fullPath: '/ScrollToCell'
      preLoaderRoute: typeof ScrollToCellLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RowsReordering': {
      id: '/RowsReordering'
      path: '/RowsReordering'
      fullPath: '/RowsReordering'
      preLoaderRoute: typeof RowsReorderingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RowGrouping': {
      id: '/RowGrouping'
      path: '/RowGrouping'
      fullPath: '/RowGrouping'
      preLoaderRoute: typeof RowGroupingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ResizableGrid': {
      id: '/ResizableGrid'
      path: '/ResizableGrid'
      fullPath: '/ResizableGrid'
      preLoaderRoute: typeof ResizableGridLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RangeSelection': {
      id: '/RangeSelection'
      path: '/RangeSelection'
      fullPath: '/RangeSelection'
      preLoaderRoute: typeof RangeSelectionLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/NoRows': {
      id: '/NoRows'
      path: '/NoRows'
      fullPath: '/NoRows'
      preLoaderRoute: typeof NoRowsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/MillionCells': {
      id: '/MillionCells'
      path: '/MillionCells'
      fullPath: '/MillionCells'
      preLoaderRoute: typeof MillionCellsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/MasterDetail': {
      id: '/MasterDetail'
      path: '/MasterDetail'
      fullPath: '/MasterDetail'
      preLoaderRoute: typeof MasterDetailLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/InfiniteScrolling': {
      id: '/InfiniteScrolling'
      path: '/InfiniteScrolling'
      fullPath: '/InfiniteScrolling'
      preLoaderRoute: typeof InfiniteScrollingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/HeaderFilters': {
      id: '/HeaderFilters'
      path: '/HeaderFilters'
      fullPath: '/HeaderFilters'
      preLoaderRoute: typeof HeaderFiltersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CustomizableRenderers': {
      id: '/CustomizableRenderers'
      path: '/CustomizableRenderers'
      fullPath: '/CustomizableRenderers'
      preLoaderRoute: typeof CustomizableRenderersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ContextMenu': {
      id: '/ContextMenu'
      path: '/ContextMenu'
      fullPath: '/ContextMenu'
      preLoaderRoute: typeof ContextMenuLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CommonFeatures': {
      id: '/CommonFeatures'
      path: '/CommonFeatures'
      fullPath: '/CommonFeatures'
      preLoaderRoute: typeof CommonFeaturesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ColumnsReordering': {
      id: '/ColumnsReordering'
      path: '/ColumnsReordering'
      fullPath: '/ColumnsReordering'
      preLoaderRoute: typeof ColumnsReorderingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ColumnSpanning': {
      id: '/ColumnSpanning'
      path: '/ColumnSpanning'
      fullPath: '/ColumnSpanning'
      preLoaderRoute: typeof ColumnSpanningLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ColumnGrouping': {
      id: '/ColumnGrouping'
      path: '/ColumnGrouping'
      fullPath: '/ColumnGrouping'
      preLoaderRoute: typeof ColumnGroupingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CellNavigation': {
      id: '/CellNavigation'
      path: '/CellNavigation'
      fullPath: '/CellNavigation'
      preLoaderRoute: typeof CellNavigationLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Animation': {
      id: '/Animation'
      path: '/Animation'
      fullPath: '/Animation'
      preLoaderRoute: typeof AnimationLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AllFeatures': {
      id: '/AllFeatures'
      path: '/AllFeatures'
      fullPath: '/AllFeatures'
      preLoaderRoute: typeof AllFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllFeaturesRoute: AllFeaturesRoute,
  AnimationLazyRoute: AnimationLazyRoute,
  CellNavigationLazyRoute: CellNavigationLazyRoute,
  ColumnGroupingLazyRoute: ColumnGroupingLazyRoute,
  ColumnSpanningLazyRoute: ColumnSpanningLazyRoute,
  ColumnsReorderingLazyRoute: ColumnsReorderingLazyRoute,
  CommonFeaturesLazyRoute: CommonFeaturesLazyRoute,
  ContextMenuLazyRoute: ContextMenuLazyRoute,
  CustomizableRenderersLazyRoute: CustomizableRenderersLazyRoute,
  HeaderFiltersLazyRoute: HeaderFiltersLazyRoute,
  InfiniteScrollingLazyRoute: InfiniteScrollingLazyRoute,
  MasterDetailLazyRoute: MasterDetailLazyRoute,
  MillionCellsLazyRoute: MillionCellsLazyRoute,
  NoRowsLazyRoute: NoRowsLazyRoute,
  RangeSelectionLazyRoute: RangeSelectionLazyRoute,
  ResizableGridLazyRoute: ResizableGridLazyRoute,
  RowGroupingLazyRoute: RowGroupingLazyRoute,
  RowsReorderingLazyRoute: RowsReorderingLazyRoute,
  ScrollToCellLazyRoute: ScrollToCellLazyRoute,
  TreeViewLazyRoute: TreeViewLazyRoute,
  VariableRowHeightLazyRoute: VariableRowHeightLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
